-- MySQL Script generated by MySQL Workbench
-- jue 02 oct 2014 10:26:21 ART
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorio` DEFAULT CHARACTER SET latin1 ;
USE `laboratorio` ;

-- -----------------------------------------------------
-- Table `laboratorio`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `medMax` DOUBLE NULL DEFAULT NULL,
  `medMin` DOUBLE NULL DEFAULT NULL,
  `pesoMax` DOUBLE NULL DEFAULT NULL,
  `pesoMin` DOUBLE NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `laboratorio`.`producto_control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`producto_control` (
  `idproducto_control` INT(11) NOT NULL AUTO_INCREMENT,
  `idProducto` INT(11) NULL DEFAULT NULL,
  `medMedia` DOUBLE NULL DEFAULT NULL,
  `medPeso` DOUBLE NULL DEFAULT NULL,
  `error` INT(11) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idproducto_control`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



ALTER TABLE producto ADD doblePeso boolean AFTER fecha;

